Fix task order placement

diff --git a/.github/workflows/GitHub Action Backend.yml b/.github/workflows/GitHub Action Backend.yml
--- a/.github/workflows/GitHub Action Backend.yml
+++ b/.github/workflows/GitHub Action Backend.yml
@@ -7,8 +7,35 @@ on:
     branches: ["main", "develop-did", "develop-fong"]
 
 jobs:
-  test:
+  build:
     runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Set up Go
+        uses: actions/setup-go@v4
+        with:
+          go-version: 1.22
+          cache: true
+
+      - name: Build
+        id: build
+        run: |
+          go build -v -o app main.go || exit 1
+        continue-on-error: true
+
+      - name: Check build result
+        if: ${{ steps.build.outcome != 'success' }}
+        run: echo "Build stage failed."
+        id: build_failed
+
+    outputs:
+      build_status: ${{ steps.build.outcome }}
+
+  unit_test:
+    runs-on: ubuntu-latest
+    needs: build
 
     steps:
       - uses: actions/checkout@v4
@@ -52,6 +79,7 @@ jobs:
 
   integration_test:
     runs-on: ubuntu-latest
+    needs: build
 
     services:
       postgres:
@@ -122,40 +150,13 @@ jobs:
     outputs:
       outcome: ${{ steps.integration_test.outcome }}
 
-  build:
-    runs-on: ubuntu-latest
-    needs: [test, integration_test]
-
-    steps:
-      - uses: actions/checkout@v4
-
-      - name: Set up Go
-        uses: actions/setup-go@v4
-        with:
-          go-version: 1.22
-          cache: true
-
-      - name: Build
-        id: build
-        run: |
-          go build -v -o app main.go || exit 1
-        continue-on-error: true
-
-      - name: Check build result
-        if: ${{ steps.build.outcome != 'success' }}
-        run: echo "Build stage failed."
-        id: build_failed
-
-    outputs:
-      build_status: ${{ steps.build.outcome }}
-
   notify:
-    needs: [test, integration_test, build]
+    needs: [unit_test, integration_test, build]
     runs-on: ubuntu-latest
     steps:
       - name: Send Discord notification
         run: |
-          UNIT_TEST_STATUS="${{ needs.test.outputs.outcome }}"
+          UNIT_TEST_STATUS="${{ needs.unit_test.outputs.outcome }}"
           INTEGRATION_TEST_STATUS="${{ needs.integration_test.outputs.outcome }}"
           BUILD_STATUS="${{ needs.build.outputs.build_status }}"
 
