Try out new github action commmand

diff --git a/.github/workflows/GitHub Action Backend.yml b/.github/workflows/GitHub Action Backend.yml
--- a/.github/workflows/GitHub Action Backend.yml
+++ b/.github/workflows/GitHub Action Backend.yml
@@ -9,6 +9,8 @@ on:
 jobs:
   test:
     runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
 
     steps:
       - uses: actions/checkout@v4
@@ -30,17 +32,9 @@ jobs:
       - name: Tidy Go modules
         run: go mod tidy
 
-      - name: Clear Go module cache if needed
-        run: go clean -modcache
-        if: failure()
-
-      # - name: Cache Go modules
-      #   uses: actions/cache@v3
-      #   with:
-      #     path: ~/go/pkg/mod
-      #     key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
-      #     restore-keys: |
-      #       ${{ runner.os }}-go-
+      # - name: Clear Go module cache if needed
+      #   run: go clean -modcache
+      #   if: failure()
 
       - name: Install dependencies
         run: go mod download
@@ -48,7 +42,7 @@ jobs:
       - name: Run Unit Tests
         id: unit_test
         run: go test -tags=unit -v ./internal/test/unit/
-        continue-on-error: true
+        # continue-on-error: true
 
       - name: Check unit test result
         if: ${{ steps.unit_test.outcome != 'success' }}
@@ -60,6 +54,8 @@ jobs:
 
   integration_test:
     runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
 
     services:
       postgres:
@@ -120,7 +116,7 @@ jobs:
           # S3_BUCKET_LOCATION: us-east-1
 
         run: go test -tags=integration -v ./internal/test/integration/
-        continue-on-error: true
+        # continue-on-error: true
 
       - name: Check integration test result
         if: ${{ steps.integration_test.outcome != 'success' }}
@@ -133,6 +129,8 @@ jobs:
   build:
     runs-on: ubuntu-latest
     needs: [test, integration_test]
+    strategy:
+      fail-fast: false
 
     steps:
       - uses: actions/checkout@v4
@@ -145,8 +143,9 @@ jobs:
 
       - name: Build
         id: build
-        run: go build -v -o app main.go
-        continue-on-error: true
+        run: |
+          go build -v -o app main.go || exit 1
+        # continue-on-error: true
 
       - name: Check build result
         if: ${{ steps.build.outcome != 'success' }}
